# Rename this file to languages.toml to enable multilingual support
[zh]
languageName = "中文"
languagedirection = "ltr"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1