# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Livinfly"
    [social.params]
    icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Mengmm_JhaiL"
    [social.params]
    icon = "brand-twitter"

[[social]]
identifier = "Email"
name = "Email"
url = "mailto:luojie3m@163.com"
    [social.params]
    icon = "email"